config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  namespace :admin do
    resources :jobs
    resources :job_arrays
    resources :users
    resources :companies
    resources :cities
    resources :states
    resources :connection_types
    resources :letter_types
    resources :stamps
    resources :conditional_ground_snow_loads

    root to: "users#index"

    get 'job/:id/generate_report', to: 'jobs#generate_report', as: :generate_report
    get 'job/:id/generate_image', to: 'jobs#generate_image', as: :generate_image
    get 'job/:id/email_to_client', to: 'jobs#email_to_client', as: :email_to_client
    patch 'job/:id/mark_approved', to: 'jobs#mark_approved', as: :mark_approved
    patch 'job/:id/mark_rejected', to: 'jobs#mark_rejected', as: :mark_rejected
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :jobs
  resources :company

  get 'job/:id/generate_report', to: 'jobs#generate_report', as: :generate_report
  get '/company/:id/confirm', to: "company#confirm", as: :company_confirm
  get '/company/:id/confirmed', to: "company#confirmed", as: :company_confirmed
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index

  end
end

app/views/visitors/index.html.slim
header.business-header
  .container
    .row
      / .col-lg-12
      /   h1.tagline
      /     | a leader in the solar industry for structural services.
.container
  hr
  .row
    .col-sm-8
      h2 What We Do
      p Right Angle Engineering is a leader in the solar industry for structural services. We provide certification letters, stamps of approval, and consulting services for residential and commercial buildings in the solar industry.
      p
        - if user_signed_in?
          = link_to "My Dashboard »", user_path(id: current_user.id), class: "a btn btn-default btn-lg btn-primary"
        / - else
        /   = link_to "Get An Estimate »", new_user_session_path, class: "a btn btn-default btn-lg"
    .col-sm-4
      h2 Contact Us
      address
        strong Right Angle Engineering
        br
        | 608 West 400 South
        br
        | Orem, UT 84058
        br
      address
        abbr[title="Phone"] Phone:
        |  (925) 270-5991

  hr
  .row
    .col-sm-6
      img.img-responsive.img-center[src="https://i.imgur.com/3Ny9MPg.jpg" alt=""]
    .col-sm-6
      h2 About Us
      p
        |  Right Angle Engineering is based out of Provo, UT.
        |  We have the brightest engineers in the country working
        |  with us to guarantee safety and quality on every
        |  certificate stamped. We make certification letters
        |  one less headache to worry about.
  hr
  .row
    .col-sm-6
      h2
        | Our Services
      br
      p Residential roof top solar structural roof evaluations

      p Commercial roof top solar structural roof evaluations

      p Ground mounted solar
    .col-sm-6
      img.img-responsive.img-center[src="https://i.postimg.cc/rFdL9Rqt/blue-house.jpg" alt=""]
  br

.row-section
  .colored-bg.orange.flex-row.center-row
    .item.central
      p OFFICIAL
      p Certification Letters
    .item.central
      p CERTIFIED
      p Stamps of Approval
    .item.central
      p QUALITY
      p Consulting Services
footer
  .row

    .col-lg-12
      p
        | Copyright © Right Angle Engineering 2019