config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  namespace :admin do
    resources :jobs
    resources :job_arrays
    resources :users
    resources :companies
    resources :cities
    resources :states
    resources :connection_types
    resources :letter_types
    resources :stamps
    resources :conditional_ground_snow_loads

    root to: "users#index"

    get 'job/:id/generate_report', to: 'jobs#generate_report', as: :generate_report
    get 'job/:id/generate_image', to: 'jobs#generate_image', as: :generate_image
    get 'job/:id/email_to_client', to: 'jobs#email_to_client', as: :email_to_client
    patch 'job/:id/mark_approved', to: 'jobs#mark_approved', as: :mark_approved
    patch 'job/:id/mark_rejected', to: 'jobs#mark_rejected', as: :mark_rejected
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :jobs
  resources :company

  get 'job/:id/generate_report', to: 'jobs#generate_report', as: :generate_report
  get '/company/:id/confirm', to: "company#confirm", as: :company_confirm
  get '/company/:id/confirmed', to: "company#confirmed", as: :company_confirmed
end

app/models/job.rb
class Job < ApplicationRecord
  has_one :estimate
  has_many :job_arrays

  has_many_attached :documents # letters
  has_many_attached :images # submitted images
  has_many_attached :layouts # submitted plans/layouts
  has_many_attached :roof_material_images # submitted roof material images
  belongs_to :connection_type
  belongs_to :user, optional: true
  belongs_to :company
  belongs_to :city, optional: true
  belongs_to :letter_type, optional: true

  accepts_nested_attributes_for :job_arrays

  validates :email,
            :solar_company_name,
            :client_last_name,
            :street_address,
            :city_name,
            :state,
            :zip,
            :home_elevation,
            :number_of_arrays,
            # :roof_pitch,
            presence: true

  attr_accessor :google_address_input, :street_number, :route, :administrative_area_level_1, :postal_code, :locality
  before_save :assign_priority
  before_save :match_city_name

  after_create do
    if city_is_serviced
      send_new_job_email
    else
      send_no_city_email
    end
  end

  def assign_priority
    case self.status
    when "In Review"
      self.priority = 0
    when "Approved"
      self.priority = 1
    when "Rejected"
      self.priority = 2
    when "Approved & Sent"
      self.priority = 3
    when "Rejected & Sent"
      self.priority = 4

    else
      self.priority = 0
    end
  end

  def match_city_name
    self.city_name = self.city.name
  end

  # CALLBACKS
  # before_validation do
  #   set_city

  #   if self.city
  #     set_city_fields
  #     # self.extend "Calculations::States::#{self.city.state}".constantize # this will no longer be necessary because the calculation variables will be stored in the city record
  #   else
  #     send_no_city_email
  #   end
  # end

  # after_validation do
  #   if self.city
  #     # set_static_fields
  #     # set_calculated_fields
  #   end
  # end

  # after_update do
  #   send_job_pdf_email if send_pdf == true
  # end



  # # INSTANCE METHODS
  # def set_city
  #   city_results = City.detect_by_name(city_name, state)
  #   self.city_id = city_results.first.id if city_results
  # end

  # def set_city_fields
  #   puts "Here's where we start doing calculations!"
  #   # self.city_elevation = city.elevation
  #   # self.ground_snow_load_pressure = city.ground_snow_load_pressure
  #   # self.design_wind_speed = city.design_wind_speed
  # end

  # # CUSTOM VALIDATIONS
  # def city_state_exists
  #   return if city_name.blank?

  #   if city_id.blank?
  #     errors.add(city_name, "is a city we don't do business in currently, but we hope to soon! We'll reach our shortly!")
  #   end
  # end

  # def job_has_all_fields
  #   attributes.select {|attr| self[attr].nil? }.count.zero?
  # end

  # EMAILS
  def send_no_city_email
    JobMailer.no_city_email(self).deliver_later
  end

  # def send_job_pdf_email
    # return false unless job_has_all_fields
    # DocumentMailer.with(job: self).job_pdf_email.deliver_later
  # end

  def send_new_job_email
    JobMailer.new_job_email(self).deliver_later
  end


  ##### NEW STUFF ######



  def city_is_serviced
    return !self.city_id.blank?
  end

  # creation method
    # create a JOB in the database that has all the user form inputs calculated out correctly
    # send out emails for new job / no city support email & customer confirmation of submission
    # create/generate document in document.rb, by pulling in the newly created JOB record

end

app/controllers/admin/jobs_controller.rb
require 'net/http'

module Admin
  class JobsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:

    def index
      search_term = params[:search].to_s.strip
      resources = Administrate::Search.new(scoped_resource,
                                           dashboard_class,
                                           search_term).run
      resources = apply_resource_includes(resources.order(priority: :asc, created_at: :asc, ))
      resources = order.apply(resources)
      resources = resources.page(params[:page]).per(25)
      page = Administrate::Page::Collection.new(dashboard, order: order)

      render locals: {
        resources: resources,
        search_term: search_term,
        page: page,
        show_search_bar: show_search_bar?,
      }
    end

    def show
      @job = Job.find(params[:id])
      @job_arrays = @job.job_arrays
      puts "This job has #{@job_arrays.count} arrays."
    end

    def generate_report
      @job = Job.find params[:id]

      if @job.documents.count > 0 && params[:fromcache]
        pdf = CombinePDF.parse Net::HTTP.get_response(URI.parse(@job.documents.first.service_url)).body
        respond_to do |format|
          format.pdf do
            send_data pdf.to_pdf, filename: "#{@job.company.name}-#{@job.client_last_name}-#{Date.today}-report", type: "application/pdf"
          end
        end and return
      end

      @job.job_arrays.each do |ja|
        begin
          ja.run_calculation
        rescue => exception
          @exception = exception
          break
          puts "Ooops. There was an error: #{exception}"
        end
      end

      if @exception
        respond_to do |format|
          format.pdf do
            render pdf: "ERROR: #{@job.company.name}-#{@job.client_last_name}-#{Date.today}-report",
              template: "documents/error.pdf.slim",
              viewport_size: '1280x1024',
              locals: {:error => @exception}
            return
          end
        end
      end

      @final_pdf = CombinePDF.new
      @stamp_pdf = CombinePDF.new
      @letter_type = @job.letter_type || @job.company.letter_type || @job.city.letter_type
      @estimate = @job.estimate
      @stamp_url = !@job.city.stamp.nil? ? @job.city.stamp.image.service_url : @job.city.state.stamps.length > 0 ? @job.city.state.stamps.active.first.image.service_url : ""
      all_uploaded_layouts = @job.layouts
      all_uploaded_images = @job.images
      all_uploaded_roof_material_images = @job.roof_material_images

      layout_pdfs = get_attachments_that_are_pdfs(all_uploaded_layouts)
      image_pdfs = get_attachments_that_are_pdfs(all_uploaded_images)
      roof_material_pdfs = get_attachments_that_are_pdfs(all_uploaded_roof_material_images)

      @pdf_ready_images = all_uploaded_images.select { |upload| !upload.blob.content_type.include? "pdf" }
      @pdf_ready_layouts = all_uploaded_layouts.select { |upload| !upload.blob.content_type.include? "pdf" }
      @pdf_ready_roof_material_images = all_uploaded_roof_material_images.select { |upload| !upload.blob.content_type.include? "pdf" }

      report_pdf = render_to_string(
        pdf: "report.pdf",
        template: "documents/letter.pdf.slim",
        viewport_size: '1280x1024',
        locals: {
          :job => @job
        }
      )
      @final_pdf << CombinePDF.parse(report_pdf)

      stamp_pdf = render_to_string(
        pdf: "stamp.pdf",
        template: "documents/stamp.pdf.slim",
        viewport_size: '1280x1024',
        locals: {
          :stamp_url => @stamp_url
        }
      )
      @stamp_pdf << CombinePDF.parse(stamp_pdf).pages[0]

      @page = 0

      if @pdf_ready_images.length > 0
        @pdf_ready_images.each do |image|
          pdf_page = get_image_pdf(image)
        end
      end

      if @pdf_ready_layouts.length > 0
        @pdf_ready_layouts.each do |image|
          pdf_page = get_image_pdf(image)
        end
      end

      if @pdf_ready_roof_material_images.length > 0
        @pdf_ready_roof_material_images.each do |image|
          pdf_page = get_image_pdf(image)
        end
      end

      if layout_pdfs.length > 0
        layout_pdfs.each do |layout|
          layout_pdf = CombinePDF.parse(Net::HTTP.get_response(URI.parse(layout.service_url)).body, {allow_optional_content: true})
          layout_pdf.pages.each {|page| page << @stamp_pdf.pages[0] }
          @final_pdf << layout_pdf
        end
      end

      if image_pdfs.length > 0
        image_pdfs.each do |image|
          image_pdf = CombinePDF.parse(Net::HTTP.get_response(URI.parse(image.service_url)).body, {allow_optional_content: true})
          image_pdf.pages.each {|page| page << @stamp_pdf }
          @final_pdf << image_pdf
        end
      end

      if roof_material_pdfs.length > 0
        roof_material_pdfs.each do |image|
          roof_material_pdf = CombinePDF.parse(Net::HTTP.get_response(URI.parse(image.service_url)).body, {allow_optional_content: true})
          roof_material_pdf.pages.each {|page| page << @stamp_pdf }
          @final_pdf << roof_material_pdf
        end
      end

      @job.documents.attach(io: StringIO.new(@final_pdf.to_pdf), filename: "#{@job.company.name}-#{@job.client_last_name}-#{Date.today}-report.pdf", content_type: "application/pdf")

      respond_to do |format|
        format.pdf do
          send_data @final_pdf.to_pdf, type: 'application/pdf', filename: "#{@job.company.name}-#{@job.client_last_name}-#{Date.today}-report"
        end
      end
    end

    def generate_image
      @job = Job.find params[:id]
      @estimate = @job.estimate
      @stamp_url = @job.city.stamp.image.service_url

      respond_to do |format|
        format.pdf do
          render pdf: "#{@job.company.name}-#{@job.client_last_name}-#{Date.today}-image",
            template: "documents/image.pdf.slim",
            viewport_size: '1280x1024',
            locals: {:job => @job, :stamp_url => @stamp_url}

        end
      end
    end

    def mark_approved
      @job = Job.find params[:id]
      @estimate = @job.estimate

      @job.status = "Approved"
      @job.save!
    end

    def mark_rejected
      @job = Job.find params[:id]
      @job.status = "Rejected"
      @job.save!
    end

    def email_to_client
      job = Job.find params[:id]
      @estimate = job.estimate
      @stamp_url = !job.city.stamp.nil? ? job.city.stamp.image.service_url : job.city.state.stamps.length > 0 ? job.city.state.stamps.active.first.image.service_url : ""
      if job.documents.count == 0
        # generate the letter document

        pdf = render_to_string pdf: "#{job.company.name}-#{job.client_last_name}-#{Date.today}-report",
        template: "documents/letter.pdf.slim", encoding: "UTF-8", header: { right: '[page] of [topage]' }, locals: {:job => job, :stamp_url => @stamp_url, :estimate => @estimate}
        job.documents.attach(io: StringIO.new(pdf), filename: "#{job.company.name}-#{job.client_last_name}-#{Date.today}-report.pdf", content_type: "application/pdf", )
      end
      if job.status.downcase.include? "approved"
        job.status = "Approved & Sent"
        job.save!
        JobMailer.approved_job_email(job).deliver_later
      else
        job.status = "#{job.status} & Sent"
        job.save!
        # JobMailer.rejected_job_email(job)
      end
    end

    def get_attachments_that_are_pdfs(uploads)
      pdfs = []
      uploads.each_with_index do |upload|
        if upload.blob.content_type.include? "pdf"
          pdfs << upload
        end
      end
      return pdfs
    end

    def get_image_pdf(blob)
      @page = @page + 1
      # print_stamp = (@job.company.stamp_on_CAD || @job.city.req_stamp || @job.company.stamp_pages.include?(@page)) ? true : false
      print_stamp = false
      pdf_page = render_to_string(
        pdf: "report.pdf",
        template: "documents/image.pdf.slim",
        viewport_size: '1280x1024',
        locals: {
          :image => blob,
          :stamp_url => @stamp_url,
          :print_stamp => print_stamp
        }
      )
      @final_pdf << CombinePDF.parse(pdf_page)
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Job.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    redirect_to root_path
  end

  def new
    @job = Job.new
    @user = current_user
    @company = current_user.company
    @connection_types = ConnectionType.all
  end

  def create
    @job = Job.new(job_params)
    city = City.find_by(name: params[:job][:locality], state_id: State.find_by(name: params[:job][:administrative_area_level_1]))
    @job.city_id = city.id unless city.nil?
    @job.attributes = {
      city_name: params[:job][:locality],
      street_address: "#{params[:job][:street_number]} #{params[:job][:route]}",
      zip: params[:job][:postal_code],
      state: params[:job][:administrative_area_level_1],
      company: current_user.company,
      user: current_user,
      solar_company_name: current_user.company.name,
      email: current_user.email
    }
    if @job.save
      @job.images.attach(params[:job][:photos]) unless params[:job][:photos].nil?
      @job.roof_material_images.attach(params[:job][:roof_material_images]) unless params[:job][:roof_material_images].nil?
      @job.layouts.attach(params[:job][:layout]) unless params[:job][:layout].nil?
      job_arrays = params[:job_arrays]      
      job_arrays.each do |job_array|
        JobArray.assign_to_job(job_array, @job.id)
      end
      if city.nil?
        flash[:danger] = "We don't currently provide estimates for #{@job.city_name}, but would like to! We've received your project details. We'll reach out to you shortly."
      else
        flash[:success] = "Successfully submitted. We will be in contact soon."
      end
      redirect_to user_path(current_user)
    else
      puts @job.errors.full_messages
      flash[:danger] = @job.errors.full_messages.reverse.to_sentence
      @user = current_user
      render :new
    end
  end

  def show
    @job = Job.find params[:id]
  end

  def generate_report
    @job = Job.find params[:id]
    @estimate = @job.estimate
    @stamp_url = @job.city.stamp.image.service_url

    respond_to do |format|
      format.pdf do
        render pdf: "#{@job.company.name}-#{@job.client_last_name}-#{Date.today}-report",
          template: "documents/letter.pdf.slim",
          viewport_size: '1280x1024',
          locals: {:job => @job}
      end
    end
  end

  private

  def job_params
    params.require(:job).permit(
      :is_premanufacture_truss,
      :email,
      :solar_company_name,
      :client_last_name,
      :street_address,
      :city_name,
      :state,
      :zip,
      :roof_square_footage,
      :home_elevation,
      :roof_pitch,
      :structure_type,
      :number_of_arrays,
      :roof_material,
      :roof_framing_type,
      :company_verified_inspection,
      :connection_type_id,
      :enclosure,
      # :photos,
      # job_arrays: [
      #   :panel_quantity,
      #   :name,
      #   :ballast_weight_psf,
      #   :framing_type,
      #   :beam_span,
      #   :beams_spacing
      # ],
      # :layout => [],
      # :images => []

    )
  end
end

app/views/admin/jobs/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>

      <th class="cell-label">Client</th>
      <th class="cell-label"><a href="/admin/jobs?job%5Bdirection%5D=desc&job%5Border%5D=created_at">Submission Date</a></th>
      <th class="cell-label">Company</th>
      <th class="cell-label"><a href="/admin/jobs?job%5Bdirection%5D=asc&job%5Border%5D=status">Status</a></th>
<%# http://localhost:3000/admin/users?user%5Bdirection%5D=asc&user%5Border%5D=jobs %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <% status_color = resource.status == "In Review" ? "orange" : resource.status == "Approved" ? "green" : resource.status == "Approved & Sent" || resource.status == "Rejected & Sent" ? "blue" : "red" %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >

          <td class="cell-data">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= resource.client_last_name %>
              </a>
            <% end -%>
          </td>
          <td class="cell-data">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= resource.created_at.strftime("%m.%d.%y") %>
              </a>
            <% end -%>
          </td>
          <td class="cell-data">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= resource.company.name %>
              </a>
            <% end -%>
          </td>
          <td class="cell-data">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 style="color: <%=status_color%>"
                 >
                <%= resource.status %>
              </a>
            <% end -%>
          </td>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.delete"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/jobs/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: page.resource_name.titleize.downcase
      ),
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources %>
</section>

app/views/admin/jobs/show.html.erb
<% content_for(:title) { "Job: #{@job.client_last_name}" } %>
<% status_color = @job.status == "In Review" ? "orange" : @job.status == "Rejected" ? "red" : "green" %>
<%= csrf_meta_tag %>
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: "job"),
      [:edit, namespace, @job],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, @job) %>
  </div>
</header>

<div class="dashboard-main-view">
  <section class="sectional">
    <div class="summary">
      <div class="summary-collection left">
        <dt class="attr-label">Status:</dt>
        <dd class="attr-data" id="job-status"
        style="color: <%=status_color%>"><%= @job.status %></dd>
        <dt class="attr-label">Submission Date:</dt>
        <dd class="attr-data"><%= @job.created_at.strftime('%a, %b %d, %Y') %></dd>
      </div>

      <div class="summary-collection">
        <dt class="attr-label">Options:</dt>
        <%= link_to "Approve", "#", id: "mark-accepted", data: {job_id: @job.id }, class: "button margin-top green"%>
        <%= link_to "Reject", "#", id: "mark-rejected", data: {job_id: @job.id }, class: "button margin-top danger"%>
      </div>
      <div class="summary-collection">
        <dt class="attr-label">Actions:</dt>
        <% ready = @job.city.is_missing_required_fields ? "none" : "block" %>
        <% notready = @job.city.is_missing_required_fields ? "block" : "none" %>
        <div style="display: <%= ready %>">
          <%= link_to "Generate PDF Report", admin_generate_report_path(format: :pdf), class: "button margin-top", target: "_blank"  %>
          <% if @job.documents.count > 1 %>
            <%= link_to "View Stored PDF Report", admin_generate_report_path(format: :pdf, :fromcache => true), class: "button margin-top", target: "_blank"  %>
          <% end %>
          <%# <%= link_to "View PDF Image", admin_generate_image_path(format: :pdf), class: "button margin-top", target: "_blank"  %>
          <% show = @job.status != "In Review" ? "block" : "none" %>
          <%= link_to "Send Report via Email", "#", class: "button margin-top", style: "display: #{show}", id: "send-email" %>
        </div>
        <div style="display: <%= notready %>">
        <p style="max-width: 300px">Prior to generating a report, please fill out the needed details for this job's city.</p>
        <%= link_to "Update #{@job.city.name}", edit_admin_city_path(@job.city.id) %>
        </div>
      </div>
    </div>
  </section>
  <hr />
  <h1 style="margin-bottom: 30px;">Submitted Data</h1>
  <section class="sectional">
    <div class="job-attributes-container">
      <% @job.attributes.except("created_at", "updated_at", "roof_pitch", "letter_type", "roof_square_footage", "user", "roof_framing_type").each do |attribute, value| %>
        <div class="dashboard-item">
          <dt class="attr-label" id="<%= attribute %>">
          <%= t(
            "helpers.label.#{resource_name}.#{attribute}",
            default: attribute.titleize,
          ) %>
          </dt>

          <dd class="attr-data"
              ><%= value == false ? "No" : value == true ? "Yes" : value == nil ? 'Not Entered' : value %></dd>
        </div>

      <% end %>
    </div>
  </section>
  <section class="sectional">
    <h1 class="section-title">Arrays</h1>
    <div class="job-attributes-container">
      <% if @job_arrays.length == 0 %>
        <p>No arrays for this job were entered.</p>
      <% else %>
        <% @job_arrays.each do |job_array| %>
          <% job_array.attributes.except("id", "job_id", "created_at", "updated_at").each do |attribute, value| %>
            <% if attribute == "framing_type_other" && job_array.framing_type_is_other == false then next end %>
          <div class="dashboard-item">
            <dt class="attr-label" id="<%= attribute %>">
              <%= t(
                    "helpers.label.#{resource_name}.#{attribute}",
                    default: attribute.titleize,
                ) %>
              </dt>

              <dd class="attr-data"><%= value == false ? "No" : value == true ? "Yes" : value == nil ? 'Not Entered' : value == "" ? "Not Entered" : value %></dd>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <section class="sectional" style="margin-top: 24px">

    <h1 style="margin-bottom: 30px">Image uploads</h1>
    <% @job.images.each do |image| %>
      <%= image_tag url_for(image) %>
      <br />
      <%= link_to "Download", rails_blob_path(image, disposition: 'attachment') %>
      <hr />
    <% end %>
    <h1 style="margin-bottom: 30px">Layout uploads</h1>
    <% @job.layouts.each do |layout| %>

      <% if layout.blob.content_type != "application/pdf" %>
        <%= image_tag url_for(layout) %>
        <br />
        <%= link_to "Download", rails_blob_path(layout, disposition: 'attachment') %>
      <% else %>
        <p>Cannot preview PDF. You must download this file in order to view it.</p>
        <%= link_to "Download PDF", rails_blob_path(layout, disposition: 'attachment') %>
      <% end %>
      <hr />
    <% end %>
    <h1 style="margin-bottom: 30px">Roof Material uploads</h1>
    <% @job.roof_material_images.each do |image| %>
      <%= image_tag url_for(image) %>
      <br />
      <%= link_to "Download", rails_blob_path(image, disposition: 'attachment') %>
      <hr />
    <% end %>

  </section>


  <div class="modal">
    <div class="modal-body">
      <h3>Email has been queued for sending.</h3>
      <p>Please allow a few minutes for it to deliver.</p>
      <a class="button" href="#" id="dismiss-modal">Great</a>
    </div>
  </div>
</div>

app/views/admin/jobs/show.html.slim
header.main-content__header[role="banner"]
  h1.main-content__page-title
    = %"Job: #{@job.client_last_name}"
  div
    = link_to(t("administrate.actions.edit_resource", name: @job.client_last_name), [:edit, namespace, @job], class: "button" ) if valid_action?(:edit) && show_action?(:edit, @job)
section.main-content__body
  dl
    - @job.attributes.each do |attribute, value|
      |  <dt class="attribute-label" id="
      = attribute
      | ">
      = t("helpers.label.#{resource_name}.#{attribute}", default: attribute )
      | </dt>
      | <dd class="attribute-data">
      = value
      | </dd>
      / = render_field attribute, page: value