config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  namespace :admin do
    resources :jobs
    resources :job_arrays
    resources :users
    resources :companies
    resources :cities
    resources :states
    resources :connection_types
    resources :letter_types
    resources :stamps
    resources :conditional_ground_snow_loads

    root to: "users#index"

    get 'job/:id/generate_report', to: 'jobs#generate_report', as: :generate_report
    get 'job/:id/generate_image', to: 'jobs#generate_image', as: :generate_image
    get 'job/:id/email_to_client', to: 'jobs#email_to_client', as: :email_to_client
    patch 'job/:id/mark_approved', to: 'jobs#mark_approved', as: :mark_approved
    patch 'job/:id/mark_rejected', to: 'jobs#mark_rejected', as: :mark_rejected
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :jobs
  resources :company

  get 'job/:id/generate_report', to: 'jobs#generate_report', as: :generate_report
  get '/company/:id/confirm', to: "company#confirm", as: :company_confirm
  get '/company/:id/confirmed', to: "company#confirmed", as: :company_confirmed
end

app/views/documents/error.pdf.slim
/ substitutions = {
/   '{keywords}' => 'foo',
/   '{other_variable}' => 'bar'
/ }

/ substitution_regex = /#{Regexp.new(Regexp.union(substitutions.keys))}/
/ # => /(?-mix:\{keywords\}|\{other_variable\})/

/ url = "http://site1.com?keywords={keywords}&some_other_variable={other_variable}"

/ url.gsub(substitution_regex, substitutions)
/ # => "http://site1.com?keywords=foo&some_other_variable=bar"
head
  = wicked_pdf_stylesheet_link_tag "documents"
body
  p Sorry, there was an error in the calculations while generating this report.
  h5 ERROR:
  p
    = error
  h5 Backtrace
  p
    = error.backtrace

app/views/documents/image.pdf.slim
body
  .container.pdf
    = wicked_pdf_image_tag image.service_url, style: "height: 1200px; width: 900px; position: absolute; top: 0; left: 0; right: 0; bottom: 0;"
    - if print_stamp
      = wicked_pdf_image_tag stamp_url, style: "position: absolute; top: 100; left: 90; width: 150px; height: 150px;"

app/views/documents/index.html.slim
body
  .container.pdf
    .header-row
      .header.left.details.table-head

      .header.right
        = image_tag("proprietary/logo.png")
    .table-div
      .table-header
        p.font-weight-bold
          | Project: LAST NAME Residence
      .table-body
        p.table-name
          | Design Criteria:
        table.calculations
          tbody
            tr
              td.row-title
                | Design Wind Speed
              td
                | 115
              td
              td
            tr
              td.row-title
                | Risk Category
              td
                | II
              td
              td
            tr
              td.row-title
                | Wind Exposure
              td
                | C
              td
              td
            tr
              td.row-title
                | Dead Load
              td
                | 12.0
              td
                | psf
              td
            tr
              td.row-title
                | Snow Load/Live Load
              td
                | 30.0
              td
                | psf
              td
            tr
              td.row-title
                | Solar Load
              td
                | 3.0
              td
                | psf
              td
            tr
              td.row-title
                | Affected Roof Area
              td
                | 900
              td
                | ft ^ 2
              td
            tr
              td.row-title
                | Affected Solar Panels
              td
                | 15
              td
              td
            tr
              td.row-title
                | Total Area of Solar Arrays
              td
                | 262.5
              td
                | ft ^ 2
              td
    .table-div
      .table-body
        p.table-name
          | 5% Gravity Stress Increase Calculation (IEBC 2015 Section 807.4)
        table.calculations
          tbody
            tr
              td.row-title
                | Roof Dead Load
              td
                | 10800
              td
                | lbs
              td
            tr
              td.row-title
                | Roof Snow Load
              td
                | 27000
              td
                | lbs
              td
            tr
              td.row-title
                | Solar Array Load
              td
                | 787.5
              td
                | lbs
              td
            tr
              td.row-title
                | Total Stress Increase From Solar Panels
              td
                | 2.1%
              td
                | PASS - less than 5%
              td
    .table-div
      .table-body
        p.table-name
          | Solar Panel Attachment Calculations
        table.calculations
          tbody
            tr
              td.row-title
                | Wind Pressure
              td
                | 10800
              td
                | lbs
              td
            tr
              td.row-title
                | Tributary Area per Connection
              td
                | 10800
              td
                | lbs
              td
            tr
              td.row-title
                | Min embedment depth of lag screw
              td
                | 10800
              td
                | lbs
              td
            tr
              td.row-title
                | 5/16" Lag screw pullout capacity
              td
                | 10800
              td
                | lbs
              td
                | NDS 2015 Table 12.2A
            tr
              td.row-title
                | 5/16" Lag screw shear capacity
              td
                | 10800
              td
                | lbs
              td
                | NDS 2015 Table 12K
            tr
              td.row-title
                | Minimum number of connection
              td
                | 10800
              td
                | lbs
              td

app/views/documents/stamp.pdf.slim
body
  .container.pdf
    = wicked_pdf_image_tag stamp_url, style: "position: absolute; top: 100; left: 90; width: 150px; height: 150px;"